package io.rosecloud.system.persistence;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import java.time.LocalDateTime;

/**
 * MyBatis-Plus persistent entity for {@code sys_login_session}.
 * Confined to infrastructure; domain code uses {@link io.rosecloud.common.security.model.LoginSession}.
 *
 * <p>Uses {@code id} mapped to column {@code session_id} as the primary key (UUID generated by the
 * authentication success handler). The {@code token} column is indexed for
 * fast revocation lookups and may be shared across multiple session rows.
 */
@TableName("sys_login_session")
public class LoginSessionEntity {

    @TableId(value = "id", type = IdType.INPUT)
    private String id;
    private String token;
    private Long userId;
    private String username;
    private String nickname;
    private String clientIp;
    private String userAgent;
    private LocalDateTime loginAt;
    private LocalDateTime expireAt;

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getToken() { return token; }
    public void setToken(String token) { this.token = token; }

    public Long getUserId() { return userId; }
    public void setUserId(Long userId) { this.userId = userId; }

    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }

    public String getNickname() { return nickname; }
    public void setNickname(String nickname) { this.nickname = nickname; }

    public String getClientIp() { return clientIp; }
    public void setClientIp(String clientIp) { this.clientIp = clientIp; }

    public String getUserAgent() { return userAgent; }
    public void setUserAgent(String userAgent) { this.userAgent = userAgent; }

    public LocalDateTime getLoginAt() { return loginAt; }
    public void setLoginAt(LocalDateTime loginAt) { this.loginAt = loginAt; }

    public LocalDateTime getExpireAt() { return expireAt; }
    public void setExpireAt(LocalDateTime expireAt) { this.expireAt = expireAt; }
}
