package io.rosecloud.system.persistence;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import java.time.LocalDateTime;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * MyBatis-Plus persistent entity for {@code sys_login_session}.
 * Confined to infrastructure; domain code uses {@link io.rosecloud.common.security.model.LoginSession}.
 *
 * <p>Uses {@code id} mapped to column {@code session_id} as the primary key (UUID generated by the
 * authentication success handler). The {@code token} column is indexed for
 * fast revocation lookups and may be shared across multiple session rows.
 */
@TableName("sys_login_session")
@Getter
@Setter
@NoArgsConstructor
public class LoginSessionEntity {

    @TableId(value = "id", type = IdType.INPUT)
    private String id;
    private String token;
    private Long userId;
    private String username;
    private String nickname;
    private String clientIp;
    private String userAgent;
    private LocalDateTime loginAt;
    private LocalDateTime expireAt;
}
