spring:
  config:
    import:
      - optional:nacos:rosecloud-common.yaml
  application:
    name: rosecloud-notice
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}

server:
  port: 9150

management:
  endpoints:
    web:
      exposure:
        include: health,info

