spring:
  config:
    import:
      - optional:nacos:rosecloud-common.yaml
  application:
    name: rosecloud-notice
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}
      discovery:
        metadata:
          rosecloud.gateway.path: /api/v1/notice/**

server:
  port: 9150

management:
  endpoints:
    web:
      exposure:
        include: health,info

rosecloud:
  audit:
    enabled: true
