spring:
  application:
    name: rosecloud-auth
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}

server:
  port: 9120

management:
  endpoints:
    web:
      exposure:
        include: health,info

