 spring:
   config:
     import:
       - optional:classpath:rosecloud-common.yaml
       - optional:nacos:rosecloud-common.yaml
       - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
       - optional:nacos:${spring.application.name}.yaml
   application:
     name: rosecloud-notice
   profiles:
     active: ${SPRING_PROFILES_ACTIVE:dev}
   cloud:
     nacos:
       server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
       username: ${NACOS_USERNAME:}
       password: ${NACOS_PASSWORD:}
       discovery:
         metadata:
           gateway.path: /api/notice/**
 
 server:
   port: 9120
