spring:
  config:
    import:
      - optional:classpath:rosecloud-common.yaml
      - optional:nacos:rosecloud-common.yaml
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
  application:
    name: rosecloud-notice
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}
      discovery:
        metadata:
          rosecloud.gateway.path: /api/notice/**,/internal/**

server:
  port: 9150
